name: StarStruck-CI

on: 
  push:
  pull_request:
    branches: 
      - '**'

jobs:
  Linux:
    name: Linux
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Setup System
        run: |
          sudo apt-get update
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          make
